# Bronystate 3.0
# Shizuka Kamishima - 2015-11-14

title: Bronystate
url: ""
baseurl: ""
markdown: kramdown
highlighter: pygments
timezone: "America/New_York"

exclude: ["vendor","deploy-key","*.enc","*.bat","*.ini","Gemfile","Gemfile.lock","README.md"]

kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
  sass_dir: _sass

permalink: /news/:year-:month-:day-:title.html
paginate: 2
paginate_path: /news/page:num
excerpt_separator: "<!-- more -->"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
      yahNews: true
  -
    scope:
      path: "about"
    values:
      titlecat: "about"
      yahAbt: true
  -
    scope:
      path: "news"
    values:
      titlecat: "news"
      yahNews: true
  -
    scope:
      path: "help"
    values:
      titlecat: "help"
      yahHelp: true
  -
    scope:
      path: "rules"
    values:
      titlecat: "rules"
      yahRules: true
